# Build Docs using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
 vmImage: win1803

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 10.x
    - script: npm install yarn -g
    - script: yarn install
    - script: yarn build
      displayName: '安装依赖&构建'
    - powershell: |
        git config --global credential.helper store
        git config --global core.autocrlf false # 禁止自动完成标准化与转换（CRLF 与 LF 自动转换）
        git config --global user.email xxred0324@qq.com
        git config --global user.name xxred
        # Add-Content "$env:USERPROFILE\.git-credentials" "https://$env:github-token:x-oauth-basic@github.com`n"
      displayName: '配置git信息'
    - powershell: | 
        git clone https://github.com/xxred/xxred.github.io.git -b gh-pages origin_site -q
        rm origin_site/* -recurse
        Copy-Item origin_site/.git vuepress -recurse
      displayName: '下载gh-pages'
    - powershell: |
        CD vuepress
        git add -A 2>&1
        git commit -m "CI Updates" -q
        git push origin gh-pages -q
      displayName: '发布提交'